/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "drmzzuuzftrtstmefnze"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybXp6dXV6ZnRydHN0bWVmbnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NzcwMjMsImV4cCI6MjA4NjE1MzAyM30.vh8UVIZGqXcRcL-k4bxxcZEsufj-ltruV2NdYqVvuG4"